### ISSUE TITLE
Eco 9.5 issues

### ISSUE THREAD

**Issue by Bazzi89** [thomasfn/EcoCivicsImportExportMod#49]
With the new update 9.5 the CivicsImportExportMod stopped working, maybe u can update it?
[log_220310095105.log](https://github.com/thomasfn/EcoCivicsImportExportMod/files/8221756/log_220310095105.log)

**Comment by thomasfn** [comment]
My apologies for the slow response.

Since 9.5 is not out yet there is no release of this mod for it. However you can access a staging build of the mod, which is updated for 9.5, at the bottom of [this page](https://github.com/thomasfn/EcoCivicsImportExportMod/actions/runs/1878051994) (check the artifacts section).

**Comment by thomasfn** [comment]
Beta 0.4.4 released that solves this issue.
